### ISSUE TITLE
Could this project be compiled on MAC?

### ISSUE THREAD

**Issue by lbdhr** [dji-sdk/Onboard-SDK#100]
I am compiling this project on a MAC, but it always turns out that some head files cannot be found.
So can this project be compiled on a MAC platform?

**Comment by lanyusea** [comment]
could you post the error msg?

**Comment by rohitsantdji** [comment]
@lbdhr You would mainly have to modify CMake, since we have a number of checks for the OS that the OSDK is running on. The serial driver and threads are POSIX-compliant, so apart from some minor changes it should work. We have not tested this and so for now at least, we cannot support you on this - but I believe it might not be a lot of work to get it to compile and run.
