### ISSUE TITLE
M100 + TX1,run Onboard-sdk linux sample  djiosdk-linux-sample on TX1, some error encoutered.

### ISSUE THREAD

**Issue by lijiangyong01** [dji-sdk/Onboard-SDK#104]
M100 connect TX1(ubuntu 16.04 ,64bit) with usb serial,I test the usb serial with minicom on TX1, uart data can be received from M100. But I run Onboard-sdk linux sample on TX1,there are some error.  everything goes ok when M100 connect laptop (ubuntu 14.04 , 64bit) with usb serial.
M100 + TX1, error shows below:

![image](https://cloud.githubusercontent.com/assets/25099305/23780214/8316c80c-0580-11e7-942e-0c5fa4982fa5.png)
I need some help.

**Comment by lanyusea** [comment]
what's your firmware of the drone?
are you using the latest code in this repository?

**Comment by lijiangyong01** [comment]
the firmware version I got from the ios app DjiGo is 1.2.0.90+.
yeah, I'm using the latest code in this repository. did anyone encounter the same problem? thanks.

**Comment by rohitsantdji** [comment]
Could you please answer the same questions as those in Issue #77 ?

Additionally, could you please try connecting the UART to the /dev/ttyTHS2 or /dev/ttyTHS1 ports on the TX1 instead of using a USB-Serial adapter?

**Comment by lijiangyong01** [comment]
@rohitsantdji I saw the question in Issue#77 carefully, maby it's not the same question?
I haved tried the /dev/ttyTHS2 already, it's the same questions..

**Comment by natelannan-osu** [comment]
I am seeing this same issue with a TX1.  Running a Beagle Bone Black I have no issues.
Answers to questions in #77:
1.  baud rate set to 230400 in DJI Assistant and UserConfig.txt
2.  connections are correct (double checked by swapping tx and rx)
3.  api control enabled
4.  UserConfig is correctly populated with ID, Key, and Version
5.  DJI Go is on and powered
6.  pulled latest version of sdk

In addition, I am seeing some erratic serial character ouput to console when running  djiosdk-linux-sample and ptemp is null after unsigned char *ptemp = &(missionACKUnion.droneVersion.ack[0]); in getDroneVersion 

However if I use the old sample CommandlineLinux_old and I change the makefile to use osdk-core and remove any calls to getSDKVersion, setVersion and SDK_VERSION the script works fine.  ptemp is still null, but I am able to automatically activate, gain control using --CA ct 1, and take off using --FC tk 4.  I also don't see any erratic serial output.

Here is an example of erratic output from blocking linux sample:
 ▒>▒▒▒00000000000000000000000000000000▒u Automatic activation successful.
                                                      ▒t~ۈFailed to obtain control.


the old script:
Waiting input
--CA ct 1
Waiting input
STATUS setControlCallback,line 1117: Obtain control running
STATUS setControlCallback,line 1114: Obtained control successfully


any advice would be grand.  Thanks for your time

**Comment by lijiangyong01** [comment]
hi natelannan, thank you for your reply. 
I also print the  *ptemp in getDronneVersion, the value in console is NULL. it's the same question.

1. baud rate set to 230400 in DJI Assistant and UserConfig.txt
2. connections are correct (double checked by swapping tx and rx)
3. api control enabled
4. UserConfig is correctly populated with ID, Key, and Version
5. DJI Go is on and powered
6. pulled latest version of sdk

I did all of those steps.The UserConfig in newest onboard sdk ,I cann't find Version config line. Maybe the old onboard sdk need to config the version. 
As you said ,the old sample CommandlineLinux_old removed the any calls to getSDKVersion, setVersion and SDK_VERSION works fine. how can I get the old sample CommanlineLinux_old ? I  need to test the way you suggested.

thanks a lot.

**Comment by natelannan-osu** [comment]
CommandlineLinux_old is located in Onboard-SDK/sample/CommandlineLinux_old
it is no longer officially supported, but I just used it as a sanity check to make sure I was communicating correctly with the TX1.  Since the newest version of the SDK doesn't use sdk version data, you'll need to just comment out the lines that reference that.  Also, the file tree changed names, so you'll have to change the makefile to reflect those changes.  Here is specifically what I did:

Onboard-SDK/sample/CommandlineLinux_old/Makefile:
change LIBDIR = ../../lib  to LIBDIR = ../../osdk-core

Onboard-SDK/sample/CommandlineLinux_old/DJIscript/src/cmdCoreAPI.cpp:
comment out the following: 
          if (script->getApi()->getSDKVersion() != versionM100_23)
          {
            cout << "Time: " << bd.timeStamp.time << endl;
            cout << "Nano: " << bd.timeStamp.nanoTime << endl;
            cout << "Sync: " << (int)bd.timeStamp.syncFlag << endl;
          }
          else

Onboard-SDK/sample/CommandlineLinux_old/DJIscript/src/cmdSettings.cpp:
comment out:
script->adata.version = SDK_VERSION;

Onboard-SDK/sample/CommandlineLinux_old/src/main.cpp:
comment out:
api.setVersion(targetVersion);

If I remember correctly, that is all I did (I am away from the drone and TX1 at the moment).  you should be able to then make the old script in CommandlineLinux_old without compile errors.  The resultant script will be in the bin directory.  just run it without any arguments.  It automatically activated for me and then I typed the following to trigger a take off in the simulator:
--CA ct 1  (this takes control of drone if you are in F mode on the controller)
--FC tk 4 (this triggers a take off)
you can do other stuff, but I was mostly interested in doing a sanity check against the latest sample scripts since they weren't working for me using the TX1.  if anyone has any ideas why latest sample scripts aren't working for me, please let me know.

thanks much

**Comment by rohitsantdji** [comment]
Hey guys, quick update - we found and resolved a bug in our serial drivers for 64-bit ARM and 32-bit x86 architectures that fixes the erratic prints (and the actual communication itself). We're currently testing this, and we will push a hotfix in the next week.

**Comment by natelannan-osu** [comment]
@rohitsantdji Fantastic news.  Thanks so much.

**Comment by rohitsantdji** [comment]
Could you guys try to clone the 3.2 branch after the latest commit? In our tests, that did resolve the serial issue on TX1/TX2 devices.

**Comment by lijiangyong01** [comment]
@rohitsantdji thank you so much, I'll test it soon.

**Comment by natelannan-osu** [comment]
@rohitsantdji Sorry for the delay in responding to this.  I am no longer seeing issues with latest commit.  Thanks much.

**Comment by adamwathieu** [comment]
Hey guys,
Could you take a look at my issue here?
https://github.com/dji-sdk/Onboard-SDK/issues/143
Thanks

**Comment by Jai-GAY** [comment]
not really sure is it [totally solved](https://github.com/dji-sdk/Onboard-SDK/issues/374#issuecomment-421901219).
