### ISSUE TITLE
QT 3.5 Crash after running a while

### ISSUE THREAD

**Issue by kezhengtao** [dji-sdk/Onboard-SDK#226]
![image](https://user-images.githubusercontent.com/11263749/34750548-88c0cd4a-f5e2-11e7-8b93-c90de38cfaca.png)

**Comment by justwillim** [comment]
Hi kezhengtao，

Github issue only accept English report.

**Comment by justwillim** [comment]
@rohitsantdji I think this issue is because the QT sample running under a two thread serial port architecture. But in windows version QSerialPort class already have a multi-thread design. Could you help to fix this issue in the next Version? Since we have this issue for a while

//! @sa https://github.com/dji-sdk/Onboard-SDK/pull/208 https://github.com/dji-sdk/Onboard-SDK/pull/209 https://github.com/dji-sdk/Onboard-SDK/pull/210
these three PR would help.

and @kezhengtao you could use these three PR above try to temporarily fix it.

BR,
William

**Comment by kezhengtao** [comment]
I just replace  QSerialPort  with something  in Windows.h . And it's fine now.

**Comment by rohitsantdji** [comment]
Could you write about what you replaced it with? That will help the community a lot. Thanks!

**Comment by kezhengtao** [comment]
I use win serialport.See the attachment. 





在 2018-01-11 02:08:17，"Rohit Sant" <notifications@github.com> 写道：


Could you write about what you replaced it with? That will help the community a lot. Thanks!

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
