### ISSUE TITLE
onboard SDK waypoint mission has a issue 

### ISSUE THREAD

**Issue by xzq123** [dji-sdk/Onboard-SDK#304]
In the mission-sample,I use a array to reserve the longitude and latitude of waypoint ,but it shows a question waypiont_mission_pionts_too_far,so I run the initial mission-sample,but it also shows this question. 
![qq 20180418110607](https://user-images.githubusercontent.com/38491923/38923050-4e0dc1c0-432c-11e8-891b-21eaccba6842.jpg)

**Comment by rohitsantdji** [comment]
This is most likely due to your RC not having received a GPS homepoint (This needs to happen at least once). Please try the following:

1. Connect a mobile device to the RC and open DJI Go. Make sure you have an internet connection. 
2. If you are not physically in China, then in the simulator, make sure your co-ordinates are not in Mainland China. If you are in China, you will have to go through the ID system in DJI Go before you can fly missions.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
