### ISSUE TITLE
Not able to take photo using Qt sample

### ISSUE THREAD

**Issue by imkhairulikhwan** [dji-sdk/Onboard-SDK#308]
Hi and good day, 

sorry for creating another topic but I think it's completely different issue. 

I am able to run Qt sample in Windows to connect to M210, however, I am not able to take photo as it seems not responding when clicking on the button. 

I noticed when I tried to "Obtain Control", the error message "Timers cannot be started from another thread" appeared

Thank you! 

![qt dji sample - error when obtaining control timer cannot be started from different thread](https://user-images.githubusercontent.com/4214164/39178281-e184bd62-47e3-11e8-9d81-d8643991031a.PNG)

![qt - camera and gimbal control](https://user-images.githubusercontent.com/4214164/39178356-18e28e92-47e4-11e8-8c76-d772068ed3b6.PNG)

**Comment by imkhairulikhwan** [comment]
It seems that the photos and the videos are being saved indeed in the sd card. But i'd like to confirm, do we need to be concerned of the error message "Timers cannot be started from another thread" when clicking on "Obtain Control"?

Thanks!

**Comment by rohitsantdji** [comment]
The error shows up because the Qt sample does not follow a standard Qt programming model. The sample is meant only as a way to try out some DJI OSDK functionality without writing a single line of code. So I think you there won't be any problems with the Timer error - but if you intend to start programming with the SDK we would recommend the Linux samples as a better starting point.

**Comment by imkhairulikhwan** [comment]
I see. Noted on that, I realized in DJI SDK Documentation in the website also mentions that the only Linux samples will be updated from time to time and Qt samples will be obsolete over time.

Thank you!
