### ISSUE TITLE
OSDK  3.6 Build library with advanced sensing failed "Problem with archive_read_open_file()"

### ISSUE THREAD

**Issue by trungnmh90** [dji-sdk/Onboard-SDK#319]
Attempting build library on RaspberryPi with advanced sensing enabled, and I got this error `CMake Error: Problem with archive_read_open_file()`
Here is some screen shoots:
![image](https://user-images.githubusercontent.com/11627415/40099140-f22bc288-5908-11e8-9f76-8a5f269b01aa.png)

and make
![image](https://user-images.githubusercontent.com/11627415/40099172-1efc9a80-5909-11e8-853f-c8222b5c72f8.png)

I checked my tar and gunzip version and believe they work fine...
![image](https://user-images.githubusercontent.com/11627415/40099260-7cc8d296-5909-11e8-9e6f-559dc31ad5eb.png)

Any idea?

**Comment by muhammetkucuk** [comment]
```
*cd Onboard-SDK 

*gedit osdk-core/cmake-modules/External_AdvancedSensing.cmake 
```

`# Set appropriate branch name 

set(BRANCH_NAME "${LIB_NAME}-${VERSION}-${TARGET_ARCH}") 

if(NOT "${PROC_VERSION}" STREQUAL "") 

  set(BRANCH_NAME "${BRANCH_NAME}${PROC_VERSION}") 

endif()  

--------------------------------------------------------------------------------------  

`# Set appropriate branch name 

set(BRANCH_NAME "origin/advanced-sensing-2.0.1-armv8") 

if(NOT "${PROC_VERSION}" STREQUAL "") 

  set(BRANCH_NAME "origin/advanced-sensing-2.0.1-armv8") 

endif()` 

```
 *git clone https://github.com/dji-sdk/Onboard-SDK-Resources.git 

*cd Onboard-SDK-Resources 

*git checkout origin/advanced-sensing-2.0.1-armv7 

*tar -xzvf advanced-sensing-1.0.0.tar.gz 

*mkdir build && cd build && cmake –DADVANCED_SENSING=ON .. && make -j4 
```

**NOW YOU GOT ANOTHER ERROR BECAUSE OF V8 Architecture now :** 

```
*mv ../Onboard-SDK-Resources/inc ../osdk-core/advanced-sensing-2.0.1/ 

*mv ../Onboard-SDK-Resources/lib ../osdk-core/advanced-sensing-2.0.1/ 

*cmake –DADVANCED_SENSING=ON .. && make -j4
```

still advanced sensing features are not functional with RPi, but it's the way I bypassed your error.  

+ If you didn't installed libvtk6-dev package: `sudo apt install libvtk6-dev –y` then you have to reinstall opencv library from source with vtk option to install opencv viz3d which enables stereo vision.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
