### ISSUE TITLE
Reset Factory issue DJI MANIFOLD ONBoard

### ISSUE THREAD

**Issue by BellFactory** [dji-sdk/Onboard-SDK#348]
Hello. I try to reset factory of DJI Manifold by following this link below.
 https://www.skypixel.com/videos/manifold-tutorials-how-to-create-and-restore-a-system-image-mp4 
But I have an issue when I try to run this command "./nvflash --read APP system.img --bl ardbeg/fastboot.bin --go" I get this error as attachment picture. I have already check usb connection by command "lsusb" ,there is stiil "NVidia Corp.". 

Anyone Please help me. Thank you in advance
![screenshot from 2018-07-07 08-50-37](https://user-images.githubusercontent.com/40905009/42405692-a4c01ee2-81c4-11e8-9768-cae933cc7d5f.png)

**Comment by BellFactory** [comment]
Actually why I wan to reset factory manifold because I had wrong connection between A3pro dji m600 with manifold and it suddenly shutdown make me cannot boot manifold again.

**Comment by JXZhou88** [comment]
Hi BellFactory,

i have encountered quite a similar problem with my Manifold in combination with Matrice 100. In my case, the Manifold also suddenly shutdown, after i was using it only for 1 hour after purchase! I also wasn't able to boot it after this incident.

I did successfully restore factory setting for my Manifold using the commands provided in your linked video tutorial, but this issue still persisted. Since you have encountered the same malfunctioning behaviour of your Manifold, i wanted to ask whether you have found a way to solve this problem. 

Regarding your Question, i think what the command "./nvflash --read APP system.img --bl ardbeg/fastboot.bin --go" does is actually making a back-up of the existing system image on the Manifold. Have you tried the command "sudo ./flash.sh jetson-tk1 mmcblk0p1" for restoring the settings?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
