### ISSUE TITLE
M600 pro velocity control issue (maximum speed 3m/s)

### ISSUE THREAD

**Issue by geoxiyang** [dji-sdk/Onboard-SDK#459]
Hello,

We are using the example of movebypositionoffset, and changed speedFactor from 2 to 12, but the maximum speed we can get was 3m/s. The launch point is 140 meters away from the target point. We also tried to change speedFactor from 2 to 4, which increased the speed from 1 m/s to 2 m/s. However, when we change the speedFactor from 2 to 8, the speed stuck at 3 m/s. Is there something we need to change? THanks!

**Comment by dji-dev** [comment]
> Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/26607'>Zendesk ticket #26607</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Movebypositionoffset is a sample function, which is a secondary encapsulation of the positionAndYawCtrl API. Since the speed of the positionAndYawCtrl API is fixed, it cannot be adjusted. If you need to customize the speed, recommended using the velocityAndYawRateCtrl() API.

Thank you for your understanding and support, hope you a delighted life.

Best Regards,
DJI SDK Support Team
