### ISSUE TITLE
DJI onboard SDK

### ISSUE THREAD

**Issue by lxiangzi** [dji-sdk/Onboard-SDK#463]

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/27224'>Zendesk ticket #27224</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

In order to better understand and help you solve the problem, suggest you click the hyperlink on the right to fill in and submit more complete information about the problem.
https://formcrafts.com/a/dji-developer-feedback-en

Best Regards,
DJI SDK Support Team
