### ISSUE TITLE
Ronin Mx Gimbal 

### ISSUE THREAD

**Issue by miseon119** [dji-sdk/Onboard-SDK#494]
Drone:  matrice 600  
Gimbal: RoninMX
Firmware= 3.2.41.13
OSDK: 3.7  

OSDK supports two ways to send gimbal commands.  However, I have some issues when I used AngleMode. 
1. When I sent relative Angle, sometimes the command doesn't work.  Most of the cases it works.  I tested in the same program.
2. When I sent absolute Angle, sometimes the gimbal can't move correctly. For example, I sent absolute yaw pitch (0,0), gimbal stoped in (1.4, 0).  It always looks like Yaw value can't be trustable. 
  Pitch doesn't have such an issue.

Please help me!

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/31367'>Zendesk ticket #31367</a>:<br><br>Dear customer,

Thank you for contacting DJI.

According to the information you provided, we are unable to determine the cause of the problem. In order to better understand and help you solve the problem, it is recommended that you click the hyperlink on the right to fill in more detailed problem information (including the necessary log/screenshot/video), https://formcrafts.com/a/dji-developer-feedback-en

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
