### ISSUE TITLE
TimeStamp for Matrice 600 pro

### ISSUE THREAD

**Issue by DimaNyumovich** [dji-sdk/Onboard-SDK#500]
Hi all.
My problem now is that when my application works with Matrice 100  - all right, but when I use Martice 600 pro - I can't get TimeStamp in telemetry... always 0. May be you have ideas what may be wrong.

Best regards,
Dmitry.

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/31857'>Zendesk ticket #31857</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

According to the information you provided, we are unable to determine the cause of the problem. In order to better understand and help you solve the problem, it is recommended that you click the hyperlink on the right to fill in more detailed problem information (including the necessary log/screenshot/video), https://formcrafts.com/a/dji-developer-feedback-en

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
