### ISSUE TITLE
Way to emergency stop Matrice 100

### ISSUE THREAD

**Issue by kanglei1130** [dji-sdk/Onboard-SDK#502]
It seems emergencyStop is not supported for M100, and so as killSwitch. 

disArm is not able to be called when drone is in the air. 

We are developing a tracking method to see anything unexpected happened, i.e., hit a tree or something. 

Anyway we can stop the engines by sending out a command to M100?

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/31885'>Zendesk ticket #31885</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Sorry, the "KillSwitch" function does not support DJI M100. Currently, it only supports the M210 series, M210 V2 series, M600 pro, A3, and N3 FC.
In addition, "disArm" is not allowed to be used while the aircraft is still in the air. And suggest that you can provide more detailed information about "emergencyStop" inability to use it. In order to better understand and help you solve the problem, it is recommended that you click the hyperlink on the right to fill in more detailed problem information (including the necessary log/screenshot/video), https://formcrafts.com/a/dji-developer-feedback-en

And if you have requirements for relevant functionality, It is recommended that you click on the links on the right side of the fill in the relevant demand information, https://formcrafts.com/a/dji-developer-feedback-en
In order to better match your requirements, try to include the following information when filling in：
1. Desired functions and requirements
2. Company/organization profile
3. Project descriptions that use this feature requirement.
4. Personal background or brief introduction.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
