### ISSUE TITLE
Could I use DJI M100 or DJI M210 fully autonomous based on OSDK without remote controller

### ISSUE THREAD

**Issue by frontw** [dji-sdk/Onboard-SDK#508]
Hi!

Is it possible to use DJI M100 or DJI M210 for tasks with full automation, where no operator and remote controller are present?
By practice, I couldnt't aquire OSDK control when remote controller is turned off. Is it possible to avoid it?

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/32703'>Zendesk ticket #32703</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

The DJI Onboard SDK supports controlling M100 or M210 without remote control but requires personnel to manually turn on the power switch of the aircraft.
You can refer to the relevant Settings, https://developer.dji.com/onboard-sdk/documentation/guides/component-guide-control-authority.html#remote-controller-lost
Another thing to note, it is necessary to open the remote control to connect with DJI GO APP for initialization information authentication. Otherwise, it can only operate within the cylinder with a radius of 50m and a height of 30m, so it is suggested that you can first turn on the remote control connection DJI GO (for initialization information authentication), so as to cancel such range limit, and then you can choose to turn off RC.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
