### ISSUE TITLE
*.cmake can bot be installed

### ISSUE THREAD

**Issue by kyleYehh** [dji-sdk/Onboard-SDK#518]
For osdk4.0, when sudo make install, *.h and *.a can be installed, but it does not install *.cmake automatically. I tried to debug but failed and I think there is something wrong in the CMakeLists.txt.

**Comment by plangenh** [comment]
I am also having problems with cmake on a raspberry pi. 
when I try to "`make`" it says `make: *** No targets specified and no makefile found.  Stop.`

**Comment by dji-dev** [comment]
@plangenh @kyleYehh  Sorry, according to the information you provided, we are unable to determine the cause of the problem. In order to better understand and help you solve the problem, it is recommended that you click the hyperlink on the right to fill in more detailed problem information (including the necessary log/screenshot/video), https://formcrafts.com/a/dji-developer-feedback-en
