### ISSUE TITLE
Issues with yaw reference frame regarding gimbal and vehicle.

### ISSUE THREAD

**Issue by jaehanIm** [dji-sdk/Onboard-SDK#738]
Hello,

I'm writing this issue since i've found some confusing phenomena regarding yaw reference frame of gimbal and the vehicle.
I'm currently working on with H20 gimbal attached to M300. Gimbal yaw control mode is set to 'absolute' mode, which makes gimbal to interpret yaw angle command based on NED frame.

However, I've found that the yaw reference frame between the drone and gimbal mismatches when the drone updates its own yaw reference frame. For example, when M300 is turned on, the initial heading value of the vehicle is initialized and at the same time, the gimbal aligns with the vehicle. At this stage when i order gimbal cmd 0, it heads North based on the initial NED frame set when it was first initialized. (This was verified by looking at controller display. Compass North matches with gimbal symbol (yellow sign on compass)

I'm not sure about the exact logic, but i've found that the drone updates its orientation reference when the number of GPS is changed or the homepoint is updated. During this stage, something strange happens. As the NED frame of the vehicle is updated, the gimbal's reference doesn't seem to be updated. From this point, the yaw order given to vehicle (say, 0 deg, or North) doesn't actual match with the yaw frame that vehicle is perceiving. (the North of vehicle frame does not match with gimbal's North)

I'm having problem due to this phenomena. By carrying on several test, i strongly doubt that there is an reference frame update issue between gimbal and vehicle. (Vehicle's yaw reference is updated, but this doesn't apply to gimbal)

I'm looking forward to having help with this issue.
Thank you very much :)
JH. Im.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/44287'>Zendesk ticket #44287</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

1、If the reference system update is related to GPS, it is possible to design the difference between geomagnetic north and geographic north, as follows：
If the drone knows its latitude and longitude information(ever searched for satellites after startup), the magnetic declination information is automatically calculated, and yaw angle's reference  is based on the geographic north.
Otherwise, the satellite has never been searched, the yaw angle reference  will only be geomagnetic north.

2、If there is a YAW change during the flight of the drone, the gimbal is inconsistent with the drone head, it is still being optimized, you can temporarily set the following parameters: is_yaw_control_invalid=1 and invoke the API：resetSync before the flight
 ![](https://djisdksupport.zendesk.com/attachments/token/B1aqlyaUKCIYTwyeYJ7ysodPn/?name=inline-1829815373.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/B1aqlyaUKCIYTwyeYJ7ysodPn' target='zd_attach'>inline-1829815373.png</a>
