### ISSUE TITLE
Read Batteries and Camera serial number with the onboard SDK version 4.1 Matrice 300 RTK

### ISSUE THREAD

**Issue by samanaz** [dji-sdk/Onboard-SDK#808]
Hi,

We are working on Matrice 300 RTK, the onboard SDK version that we are using is 4.1 2end Feb release.

We would like to read the batteries and camera serial numbers through onboard SDK.

Would you please guide us how we can do that.

Thank you.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/50134'>Zendesk ticket #50134</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry, OSDK can't read serial numbers of batteries and camera.

If you have requirements for relevant functionality, It is recommended that you click on the links on the right side and fill in the relevant demand information,  https://djisdksupport.zendesk.com/hc/en-us/requests/new
In order to better match your requirements, try to include the following information when filling in：
1. Desired functions and requirements
2. Company/organization profile
3. Project descriptions that use this feature requirement.
4. Personal background or brief introduction.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>
