### ISSUE TITLE
Zoom is not applied after calling setOpticalZoomFactorSync

### ISSUE THREAD

**Issue by MH2033** [dji-sdk/Onboard-SDK#817]
After calling this API to set the zoom factor for the main camera the zoom factor is set and can even be seen from the radio controller but the setting is not applied unless i change the mode from wide to zoom from the controller and i couldn't find the correct API to do the same thing using the OSDK. Am i missing something here? Regards

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51223'>Zendesk ticket #51223</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/51223'>Zendesk ticket #51223</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

setOpticalZoomFactorSync only supports the Zoom lens. And OSDK provides API to change the camera lens:
  LiveViewErrCode changeH264Source(LiveViewCameraPosition pos, LiveViewCameraSource source);

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by MH2033** [comment]
Thank you very much, this was the correct API to call
Best regards
