### ISSUE TITLE
P1 getting bin and mrk files

### ISSUE THREAD

**Issue by deadman2000** [dji-sdk/Onboard-SDK#819]
In the request for a list of files from the camera P1, only media is received. But we need both bin and mkr too. Is support for these files planned? Or is this a bug and will be fixed?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51409'>Zendesk ticket #51409</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/51409'>Zendesk ticket #51409</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Do you develope OSDK application and use P1? OSDK has not yet adapted to P1, it will be adapted in the next version.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by dji-kyle** [comment]
PSDK 3.x has been released and adapted to P1
