### ISSUE TITLE
Image ISO Manifold 2-G

### ISSUE THREAD

**Issue by Caufmann** [dji-sdk/Onboard-SDK#820]
Hi,

I'm currently working on manifold 2-G and I was looking for it's ISO Image.

Using this link : https://www.dji.com/fr/manifold-2/downloads , I can't find any ISO Image in the "Manifold 2 - Firmware V0.3.3.2 (Manifold 2-G Image Tool & Official Image)".gz file.

Could you give me some hints to find it, or provide it somehow ?

Looking forward to hearing from you,

Clément

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51679'>Zendesk ticket #51679</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/51679'>Zendesk ticket #51679</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Regarding the Manifold2 image file, it is recommended to directly consult the product after-sales service: support@dji.com

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by IuliuNovac** [comment]
You don't need an iso for manifold 2-G, it's not the c version. What you need is to follow DJI manifold 2-g documentation to unzip the gz archive and run the correct commands from a ubuntu machine to install the os of the manifold 2G. The manifold 2G is a jetson tx with a custom carrier, so you should treat it accordingly. Don't try to install it with the jetpack, because the DJI screwed up a here, instead of releasing the config file of the board pin configuration, they wrapped it into in the 3.3.2 version from jetpack and now you can't run the newest version for jetsons, but only the last ubuntu 16. I have tried to extract it, but due to lack of knowledge, I have failed.
