### ISSUE TITLE
Getting recording status and zoom mode

### ISSUE THREAD

**Issue by MH2033** [dji-sdk/Onboard-SDK#821]
Hi,

OSDK provides APIs for changing the camera source(changeSourceH264) and video recording. But are there any APIs to get the recording status and zoom mode from the flight controller?(in case the user changed these using the radio controller)

Regards

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51752'>Zendesk ticket #51752</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/51752'>Zendesk ticket #51752</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry，OSDK does not support to get the lens mode. but there is an API to get camera working mode:
  /*! @brief get camera working mode, blocking calls
  *
  *  @platforms M210V2, M300
  *  @note All the APIs whose name ending with sync or async in this class
  * have a restriction on calling. All these API should not be called until
  * the previous request receives ack or timeout.
  *  @param index camera module index, input limit see enum
  * DJI::OSDK::PayloadIndexType
  *  @param workingMode used as an output param, camera working mode, input
  * limit see enum DJI::OSDK::CameraModule::WorkMode
  *  @param timeout blocking timeout in seconds
  *  @return ErrorCode::ErrorCodeType error code
  */
  ErrorCode::ErrorCodeType getModeSync(PayloadIndexType index,
                                      CameraModule::WorkMode &workingMode,
                                      int timeout);

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by MH2033** [comment]
Thank you for your response

I've already worked with the mentioned API but this API only returns the working mode of the camera but it doesn't inform the caller if it's in the recording state or not
