### ISSUE TITLE
相机管理

### ISSUE THREAD

**Issue by JunGenius** [dji-sdk/Onboard-SDK#839]
你好 , 咨询下几个问题。
1. OSDK 是否支持删除相册中文件功能 ? 若不支持， 该如何实现删除相册文件功能 ？ 
2. 假如相册空间不足，再拍照或者录像，是否会覆盖原文件，还是会提示无法继续拍照或录像 ？

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/55503'>Zendesk ticket #55503</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/55503'>Zendesk ticket #55503</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

很抱歉，当前OSDK仅支持M300提供照片下载功能，不支持对相机SD卡文件进行操作和管理，需要通过遥控器APP端进行操作。

SD卡内存不够时，执行拍照会报错，无法继续拍照和录像。

另关于OSDK对SD卡的管理，该功能已经提交进行评估，您可以继续关注SDK相关功能的后续更新。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
