### ISSUE TITLE
M300 RTK  OSDK integration with QT

### ISSUE THREAD

**Issue by dt-developer1** [dji-sdk/Onboard-SDK#840]
I am using M300 RTK, Trying to develop a Way point navigation GUI Application with Latest OSDK 4.1.0 . 

1: Is Latest OSDK 4.1.0  QT Sample codes available? 
2: M300RTK support Virtaul RC ?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/55541'>Zendesk ticket #55541</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/55541'>Zendesk ticket #55541</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

1: Is Latest OSDK 4.1.0 QT Sample codes available?

-->Sorry, OSDK has stopped the update and maintenance of the QT platform sample, the OSDK Linux sample is recommended.


2: M300RTK support Virtaul RC ?

-->M300 does not support the Virtaul RC, but the joystick is avaliable.

sample:

https://github.com/dji-sdk/Onboard-SDK/tree/master/sample/platform/linux/flight-control


Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>
