### ISSUE TITLE
OSDK-raspberry support version Error

### ISSUE THREAD

**Issue by dt-developer1** [dji-sdk/Onboard-SDK#841]
I am Testing Raspberry PI as OnBoard computer. When i am testing the OSDK ( raspberrypi-support) QT sample code , i am getting error "SDK Version did not match".

1: What is mean by this error ?
2: which OSDK version support raspberry pi ?
3: What is hardware requirement (Minimum RAM, Minimum Memory,Minimum  Core) to set a Device as OnBoard Computer?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/55589'>Zendesk ticket #55589</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/55589'>Zendesk ticket #55589</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry, OSDK QT platform has stopped updating and maintenance. And OSDK version and compatible drones, please refer to the official website of the developer.
https://developer.dji.com/document/30ac6801-db84-46c2-baf2-8ad8d62bf3ba
 ![](https://djisdksupport.zendesk.com/attachments/token/tjN7otWalPi0oCLK0ygCDqLD9/?name=inline188394000.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/tjN7otWalPi0oCLK0ygCDqLD9' target='zd_attach'>inline188394000.png</a>
<br><p><em><small>°°°</small></em></p>
