### ISSUE TITLE
How to stay in mission for M300?

### ISSUE THREAD

**Issue by btsatoukzn** [dji-sdk/Onboard-SDK#843]
hi, 

For M210, WaypointActionTypeFormat.WP_ACTION_STAY exists.
There is no equivalent in the M300.
For M300, what should I do to wait during the mission?

Can it be realized by combining SampleRearchPoint and AssociateAction of DJIWaypointV2ActionTriggerType?

I was using OSDK 4.1.0 and was able to run the sample program djiosdk-waypoint-v2-sample.

Thank you.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/55840'>Zendesk ticket #55840</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/55840'>Zendesk ticket #55840</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Please refer to the link:
https://sdk-forum.dji.net/hc/en-us/articles/900005820706-How-to-set-waypoint-action-hover-in-waypoint-V2-

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by btsatoukzn** [comment]
thank you for your reply.

The contents of the above site do not have enough information on standby settings.

> DJIWaypointV2AircraftControlFlyingParam,   // stops flying --->A
> DJIWaypointV2IntervalTriggerParam,             // interval time --->B
> DJIWaypointV2AircraftControlFlyingParam,   // starts flying --->C

The action of M300 needs to set the trigger and the actuator.

A and C is actuator's parameter.
B is trigger's parameter.

What are the triggers for A and C?
What is B's actuator?

thank you.

**Comment by btsatoukzn** [comment]
I tried the following settings.
However, the drone remained stationary after 10 seconds.

A. trigger: TriggerTypeSampleReachPoint
      actuator: AircraftControlFlyingParam (isStartFlying = 0)

B. trigger: TriggerTypeInterval (interval = 100)
      actuator: AircraftControlFlyingParam (isStartFlying = 0)

C. trigger: TriggerTypeActionAssociated
      actuator: AircraftControlFlyingParam (isStartFlying = 1)

thank you.

**Comment by btsatoukzn** [comment]
I was able to confirm the operation of waiting for 10 seconds with the following settings.

A. trigger: TriggerTypeSampleReachPoint
actuator: AircraftControlFlyingParam (isStartFlying = 0)

B. trigger: TriggerTypeActionAssociated (waitingTime = 100)
actuator: AircraftControlFlyingParam (isStartFlying = 1)

Thank you.
