### ISSUE TITLE
stm32 m600pro运行实例程序 出现Topic 0xB value memory not initialized, return default问题

### ISSUE THREAD

**Issue by andsoonme** [dji-sdk/Onboard-SDK#848]

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/57011'>Zendesk ticket #57011</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/57011'>Zendesk ticket #57011</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

出错 Topic 0xA value memory not initialized, return default
-->表示订阅遥测数据未初始化，遥测订阅是通过串口来实现，建议检查串口通信的稳定性，可以在设备允许的条件下增大串口波特率测试。也可以换个机载平台（PC ubuntu虚拟环境）先确保飞机给出的数据是正常的，再排查机载端的串口通信问题。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
