### ISSUE TITLE
Is there a way to communicate to a PC on the ground?

### ISSUE THREAD

**Issue by tubzby** [dji-sdk/Onboard-SDK#854]
Hi Dji,  I'm wondering if there is any way I can connect to a TCP server on the ground while I'm in air on the drone?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/57588'>Zendesk ticket #57588</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/57588'>Zendesk ticket #57588</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

There are two suggestions for referrence:
1. The ground end is communicate with the drone through MSDK (RC), MSDK connects to the server

2. Using onboard computer + OSDK development on the drone side. The onboard computer integrates wireless communication modules and develops communication with the ground server.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by tubzby** [comment]
Thanks for the quick reply and helpful suggestion, using mobile SDK might be a good option.

Just for clarification,  is that "wireless communication modules" in option 2 mean something like WiFi/4G/5G modules, are these kinds of modules available from Dji that I can just Plug and Play?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/57588'>Zendesk ticket #57588</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Just for clarification, is that "wireless communication modules" in option 2 mean something like WiFi/4G/5G modules, are these kinds of modules available from Dji that I can just Plug and Play?
    -->Yes, "wireless communication modules" in option 2 mean something like WiFi/4G/5G modules, DJI does not provide onboard computer wireless modules, developers need to choose and develop according to actual needs.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by tubzby** [comment]
Thanks.
