### ISSUE TITLE
Using ActionExecEvent on M300

### ISSUE THREAD

**Issue by btsatoukzn** [dji-sdk/Onboard-SDK#859]
hi,

We want to handle the execution of an action in an event callback.
However, the parameter was commented out.

dji_mission_type.hpp L:844-849
>   /*ID:0x30*/
>   // struct ActionExecEvent{
>   //   uint16_t actionId;
>   //   uint8_t preActuatorState;
>   //   uint8_t curActuatorState;
>   //   uint32_t result;
 >  // }ActionExecEvent;

So, when we uncommented these and ran the sample program 'djiosdk-waypoint-v2-sample' after building, we were able to refer to the parameters.

Why is the parameter commented out?
Is it okay to use this parameter?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/58242'>Zendesk ticket #58242</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/58242'>Zendesk ticket #58242</a>:<br><br>This parameter can be uncommented and used.
<br><p><em><small>°°°</small></em></p>

**Comment by btsatoukzn** [comment]
thank you for your prompt reply.
