### ISSUE TITLE
Get status GPIO Manifold 2G

### ISSUE THREAD

**Issue by IvanOrfanidi** [dji-sdk/Onboard-SDK#865]
Hello Dear Friend!
Tell me how do I get the status of the port I/O?

![image](https://user-images.githubusercontent.com/10355755/150813627-8b426e08-4338-4018-9dcc-78489dbdcab2.png)
Or
![image](https://user-images.githubusercontent.com/10355755/150814383-6bc4be4e-f99f-428f-a747-9b55e1914011.png)

Can I use ports just to receive logic signals?

There are services: 
/dji_sdk/mfio_config 
/dji_sdk/mfio_set_value

But I don't understand which channel is needed.

How do I get the port status?

I'm sorry if the question is rather stupid, but I haven't found any documentation on them.

Is it possible to find out the status of the port directly, not through ROS?

Thanks for understanding!

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59651'>Zendesk ticket #59651</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/59651'>Zendesk ticket #59651</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

This I/O PORT corresponds to the manifold2 interface, and the SDK does not provide the manifold2 I/O control.
The MFIO function provided by the OSDK is the the drone MFIO function, but the M210/M300 no longer supports the OSDK to develop MFIO.
 ![](https://djisdksupport.zendesk.com/attachments/token/mkelEmM7eEP8P331aTf0N8Na0/?name=inline-35033442.png)​

There is also no driver for the I/O port of the manifold2 on the SDK team. It is recommended that you consult the product after-sales directly: support@dji.com.

Please note that how to use the I/O port of the Manifold2.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/mkelEmM7eEP8P331aTf0N8Na0' target='zd_attach'>inline-35033442.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by IvanOrfanidi** [comment]
Oh, I get it! Thanks!
