### ISSUE TITLE
DisplayMode = 52.

### ISSUE THREAD

**Issue by IvanOrfanidi** [dji-sdk/Onboard-SDK#870]
Hi, friend!
We had a problem with the M300 drone.
We couldn't cancel the drone's homecoming. We got an error that the drone was in DisplayMode = 52.

Here is the text:
**During landing, the drone DJI Matrice M300 with the manifold 2G failed to interrupt RTH. At the same time, the drone was in Display mode = 52. RTH at this moment was not interrupted by a command from the OSDK.
Please advise what is display mode=52**

How to cancel the landing if we are in this mode. We could not find a description of this mode:
_https://developer.dji.com/onboard-api-reference/namespaceDJI_1_1OSDK_1_1VehicleStatus_1_1DisplayMode.html_

Tell me what is displayMode = 52? 

Thank you for understanding, friend.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/60349'>Zendesk ticket #60349</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/60349'>Zendesk ticket #60349</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

 **display mode=52** means the drone enter three-propeller emergency landing，
This is an emergency landing status. Please check the drone status through the remote control and Pilot APP. If necessary, please provide the drone log and contact support@dji.com to apply for after-sales service of the drone.
 ![](https://djisdksupport.zendesk.com/attachments/token/aCCZgGPiX2bkfxq8JG69cAI43/?name=inline2092101867.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/aCCZgGPiX2bkfxq8JG69cAI43' target='zd_attach'>inline2092101867.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by IvanOrfanidi** [comment]
Thank you dear Friend!

We have already contacted the dealer.

I'm glad you always answer my questions.
