### ISSUE TITLE
remove 5 sec delay for H20 camera in OSDK

### ISSUE THREAD

**Issue by idani301** [dji-sdk/Onboard-SDK#873]
fix this in m300 
   
     cameraModel.observe(new Observer<CameraModel>() {
            @Override
            public void observe(CameraModel cameraModel, CameraModel t1, Observation<CameraModel> observation) {
                if(t1 != null){
                    observation.remove();
                    if(t1 == CameraModel.H20T || t1 == CameraModel.H20){
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try {
                                    Thread.sleep(5000);
                                } catch (InterruptedException e) {
                                    e.printStackTrace();
                                }
                                droneOsdk.currentResolution(videoStreamSource).set(new VideoResolution(1920,1080));
                            }
                        });
                    }
                }
            }
        }).observeCurrentValue();

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/60803'>Zendesk ticket #60803</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>
